// Auto-generated from client/public/new cards - do not edit manually
import { InvitationDesign } from '@/types';

export const newInvitationDesigns: InvitationDesign[] = [
  { id: "d8c94284c7f3158ab673d07f", name: 'أبيض بسيط دعوة حفل زفاف قصة', category: 'package', image: '/new cards/كلاسيك/أبيض بسيط دعوة حفل زفاف قصة.png', packageTier: 'classic' },
  { id: "c22c6f7b51a3b6081dc6d971", name: 'بطاقة دعوة عقد قران أو زواج بتصميم حديقة الفراشات', category: 'package', image: '/new cards/كلاسيك/بطاقة دعوة عقد قران أو زواج بتصميم حديقة الفراشات.png', packageTier: 'classic' },
  { id: "ccf67dd0f76e37455a1a7f86", name: 'بطاقه دعوه زواج احمر بسيط', category: 'package', image: '/new cards/كلاسيك/بطاقه دعوه زواج احمر بسيط.png', packageTier: 'classic' },
  { id: "de0fd5d5fa8093406b4efbac", name: 'دعوة (مطبوعة) اللون اخضر و ابيض وردي بسيط دعوة زواج arabic invitation leaves', category: 'package', image: '/new cards/كلاسيك/دعوة (مطبوعة) اللون اخضر و ابيض وردي بسيط دعوة زواج arabic invitation leaves.png', packageTier: 'classic' },
  { id: "abf9b3b440f3754feb67f97f", name: 'دعوة (مطبوعة) اللون الروز و ابيض وردي بسيط دعوة زفاف Pink and Cream floral arabic wedding invitation', category: 'package', image: '/new cards/كلاسيك/دعوة (مطبوعة) اللون الروز و ابيض وردي بسيط دعوة زفاف Pink and Cream floral arabic wedding invitation .png', packageTier: 'classic' },
  { id: "d619d139dd78bceed6cbc367", name: 'دعوة حفل خطبة زواج زهور انيق', category: 'package', image: '/new cards/كلاسيك/دعوة حفل خطبة زواج زهور انيق .png', packageTier: 'classic' },
  { id: "b430630808d7d6043ca66619", name: 'دعوة حفل زفاف', category: 'package', image: '/new cards/كلاسيك/دعوة حفل زفاف .png', packageTier: 'classic' },
  { id: "66368e09b577a5311796e436", name: 'دعوة حفلة زفاف بنفسجية', category: 'package', image: '/new cards/كلاسيك/دعوة حفلة زفاف بنفسجية.png', packageTier: 'classic' },
  { id: "cdcc47372573c667ee1393f7", name: 'دعوة زفاف invitation تصميم زهور بسيط لون بنفسج نمط مميز', category: 'package', image: '/new cards/كلاسيك/دعوة زفاف invitation تصميم زهور بسيط لون بنفسج نمط مميز.png', packageTier: 'classic' },
  { id: "0e8711ddf164a8681610abc9", name: 'دعوة لحفل زفاف عصرية باللون الرمادي والبيج', category: 'package', image: '/new cards/كلاسيك/دعوة لحفل زفاف عصرية باللون الرمادي والبيج  .png', packageTier: 'classic' },
  { id: "e79743f4a6bc2fcafe61fcdd", name: 'ذهبي وأبيض عصري حفل زفاف قصة', category: 'package', image: '/new cards/كلاسيك/ذهبي وأبيض عصري حفل زفاف قصة.png', packageTier: 'classic' },
  { id: "c049fbf1d864f2508e7c688e", name: 'ستوري اعلان حفل زواج اخضر بسيط', category: 'package', image: '/new cards/كلاسيك/ستوري اعلان حفل زواج اخضر بسيط.png', packageTier: 'classic' },
  { id: "0b9461e76445535795d6a916", name: 'ستوري اعلان خطوبه أحمر بسيط', category: 'package', image: '/new cards/كلاسيك/ستوري اعلان خطوبه أحمر بسيط.png', packageTier: 'classic' },
  { id: "39eae1cf29b42a66ec60d805", name: 'ستوري دعوة حفل زواج اخضر بسيط', category: 'package', image: '/new cards/كلاسيك/ستوري دعوة حفل زواج اخضر بسيط.png', packageTier: 'classic' },
  { id: "04522a26d4f633d18d5f7b98", name: 'قصة Instagram ازرق ووردي انيق دعوة حفل زفاف', category: 'package', image: '/new cards/كلاسيك/قصة Instagram ازرق ووردي انيق دعوة حفل زفاف.png', packageTier: 'classic' },
  { id: "fc1df7299aaef6084aeba51c", name: 'قصة Instagram بني ووردي انيق عن دعوة حفل زفاف', category: 'package', image: '/new cards/كلاسيك/قصة Instagram بني ووردي انيق عن دعوة حفل زفاف.png', packageTier: 'classic' },
  { id: "139a236b830b54312a1469fe", name: 'قصة انستجرام بتصميم بسيط لاعلان عقد قران', category: 'package', image: '/new cards/كلاسيك/قصة انستجرام بتصميم بسيط لاعلان عقد قران.png', packageTier: 'classic' },
  { id: "52c2c717654de6288f8e9fab", name: 'قصة انستقرام اخضر بسيط عن حفلات الزفاف', category: 'package', image: '/new cards/كلاسيك/قصة انستقرام اخضر بسيط عن حفلات الزفاف.png', packageTier: 'classic' },
  { id: "4b99e705f87acffe201bad01", name: 'قصة انستقرام دعوة زواج لون بنفسجي', category: 'package', image: '/new cards/كلاسيك/قصة انستقرام دعوة زواج لون بنفسجي .png', packageTier: 'classic' },
  { id: "e72be9f141ce7deec84d03df", name: 'قصة انستقرام رمادي و أبيض عصري دعوة خطوبة', category: 'package', image: '/new cards/كلاسيك/قصة انستقرام رمادي و أبيض عصري دعوة خطوبة.png', packageTier: 'classic' },
  { id: "06aeb879a25f1ff36d2be43d", name: 'قصة انستقرام عن تهنئة عقد قران بسيط أزرق غامق', category: 'package', image: '/new cards/كلاسيك/قصة انستقرام عن تهنئة عقد قران بسيط أزرق غامق .png', packageTier: 'classic' },
  { id: "dd9be3f5724e20b5d6cf5acd", name: 'قصة انستقرام وردي بسيط عن حفلات الزفاف', category: 'package', image: '/new cards/كلاسيك/قصة انستقرام وردي بسيط عن حفلات الزفاف.png', packageTier: 'classic' },
  { id: "6d4280b5f6fc6f65daa9dded", name: 'قصتك دعوة زفاف بني محايد بسيط', category: 'package', image: '/new cards/كلاسيك/قصتك دعوة زفاف  بني محايد بسيط .png', packageTier: 'classic' },
  { id: "01e48b1e9cf8eaf45d47b6dc", name: 'قصتك عقد قران أبيض وأخضر بسيط', category: 'package', image: '/new cards/كلاسيك/قصتك عقد قران أبيض وأخضر بسيط .png', packageTier: 'classic' },
  { id: "21890d8be285feb19685af63", name: 'قصتك عن دعوة زفاف أبيض و أسود بسيط', category: 'package', image: '/new cards/كلاسيك/قصتك عن دعوة زفاف أبيض و أسود بسيط.png', packageTier: 'classic' },
  { id: "243f1917e684715c4cd2d744", name: 'قصتك وردي بسيط عن تهنئة حفل زفاف', category: 'package', image: '/new cards/كلاسيك/قصتك وردي بسيط عن تهنئة حفل زفاف .png', packageTier: 'classic' },
  { id: "180a7e83c727a8838eac838f", name: 'Instagram دعوة حفل زفاف زهور احمر وبيج ستوري', category: 'package', image: '/new cards/بريميوم/Instagram دعوة حفل زفاف زهور احمر وبيج ستوري.png', packageTier: 'premium' },
  { id: "597e284eee5869536a1e25a4", name: 'دعوة حفل خطبة زواج زهور انيق (1)', category: 'package', image: '/new cards/بريميوم/دعوة حفل خطبة زواج زهور انيق  (1).png', packageTier: 'premium' },
  { id: "042805a30773d1001e7bd195", name: 'دعوة حفل زفاف خطبة زهور ستوري', category: 'package', image: '/new cards/بريميوم/دعوة حفل زفاف خطبة زهور ستوري.png', packageTier: 'premium' },
  { id: "e4f7ec879cb02bf158119148", name: 'دعوة حفل زفاف عامودية', category: 'package', image: '/new cards/بريميوم/دعوة حفل زفاف عامودية.png', packageTier: 'premium' },
  { id: "45d0e95d03b04a8948faea7c", name: 'دعوة زفاف بلون الابيض و الرمادى بسيطة', category: 'package', image: '/new cards/بريميوم/دعوة زفاف بلون الابيض و الرمادى بسيطة.png', packageTier: 'premium' },
  { id: "1b9242e78cb7ceb7fdce2cb4", name: 'ستوري اعلان حفل زواج بني بسيط', category: 'package', image: '/new cards/بريميوم/ستوري اعلان حفل زواج بني بسيط.png', packageTier: 'premium' },
  { id: "d46b5a34852ba892589ab616", name: 'ستوري اعلان خطوبه احمر بسيط', category: 'package', image: '/new cards/بريميوم/ستوري اعلان خطوبه احمر  بسيط.png', packageTier: 'premium' },
  { id: "1c322b3e7bfd3d3161b3b735", name: 'ستوري اعلان خطوبه بنفسجي بسيط', category: 'package', image: '/new cards/بريميوم/ستوري اعلان خطوبه بنفسجي بسيط.png', packageTier: 'premium' },
  { id: "8d237ef83c039a5943da2ba6", name: 'ستوري انستغرام اخضر اصفر مباركه زواج', category: 'package', image: '/new cards/بريميوم/ستوري انستغرام اخضر اصفر مباركه زواج .png', packageTier: 'premium' },
  { id: "5567d2c894eaa7a5048a1b55", name: 'ستوري انستغرام بنفسجي بتصميم راقي و حديث لاعلان عقد قران', category: 'package', image: '/new cards/بريميوم/ستوري انستغرام بنفسجي بتصميم راقي و حديث لاعلان عقد قران.png', packageTier: 'premium' },
  { id: "19caa66fd050c734c434a46a", name: 'ستوري انستغرام بيج و وردي بتصميم راقي و حديث لاعلان عقد قران', category: 'package', image: '/new cards/بريميوم/ستوري انستغرام بيج و وردي بتصميم راقي و حديث لاعلان عقد قران.png', packageTier: 'premium' },
  { id: "3212079e11377ccc3c4b3346", name: 'ستوري انستقرام دعوة زفاف باللون البيج و احمر', category: 'package', image: '/new cards/بريميوم/ستوري انستقرام دعوة زفاف باللون البيج و احمر.png', packageTier: 'premium' },
  { id: "4547ede776ecd48430c0ac4d", name: 'ستوري دعوة زفاف احمر وبيج بسيط', category: 'package', image: '/new cards/بريميوم/ستوري دعوة زفاف احمر وبيج بسيط.png', packageTier: 'premium' },
  { id: "c62b4f5b0bd9a85b546890cc", name: 'ستوري دعوة زفاف اخضر و ابيض بسيط', category: 'package', image: '/new cards/بريميوم/ستوري دعوة زفاف اخضر و ابيض بسيط.png', packageTier: 'premium' },
  { id: "659f79506c43fd8ce3f9bc8b", name: 'ستوري عبارة عن دعوة زفاف باللون البنفسجي و الابيض', category: 'package', image: '/new cards/بريميوم/ستوري عبارة عن دعوة زفاف باللون البنفسجي و الابيض.png', packageTier: 'premium' },
  { id: "0c4af78e431afdf5dc901330", name: 'قصة انستقرام أحمر و وردي عقد قران', category: 'package', image: '/new cards/بريميوم/قصة انستقرام أحمر و وردي عقد قران.png', packageTier: 'premium' },
  { id: "8c4d717b10ea52c5238fd398", name: 'قصة انستقرام أزرق و بيج عصري دعوة زواج', category: 'package', image: '/new cards/بريميوم/قصة انستقرام أزرق و بيج عصري دعوة زواج .png', packageTier: 'premium' },
  { id: "c606db93f942192aee6c4c45", name: 'قصة انستقرام بنفسجي لطيف دعوة زواج', category: 'package', image: '/new cards/بريميوم/قصة انستقرام بنفسجي لطيف دعوة زواج.png', packageTier: 'premium' },
  { id: "5f810055af5214a4eacab615", name: 'قصة انستقرام تهنئة زفاف بسيطة احمر غامق', category: 'package', image: '/new cards/بريميوم/قصة انستقرام تهنئة زفاف بسيطة احمر غامق.png', packageTier: 'premium' },
  { id: "2b25763c676f8c701d90bd99", name: 'قصة انستقرام رمادي أبيض وبسيط زهور دعوة زواج', category: 'package', image: '/new cards/بريميوم/قصة انستقرام رمادي أبيض وبسيط زهور دعوة زواج .png', packageTier: 'premium' },
  { id: "cc97a4da72b368a2b0833e19", name: 'قصتك ازرق بسيط عن حفلات الزفاف', category: 'package', image: '/new cards/بريميوم/قصتك ازرق بسيط عن حفلات الزفاف.png', packageTier: 'premium' },
  { id: "5d1b7f528edb632718fb5c6d", name: 'وردي وأبيض تقليدي زفاف بطاقة', category: 'package', image: '/new cards/بريميوم/وردي وأبيض تقليدي زفاف بطاقة.png', packageTier: 'premium' },
  { id: "e97c653630cb8cf0d8563e32", name: 'وردي وأبيض كلاسيكية زفاف دعوة', category: 'package', image: '/new cards/بريميوم/وردي وأبيض كلاسيكية زفاف دعوة.png', packageTier: 'premium' },
  { id: "227197804d04302d029d2dc0", name: 'وردي وأزرق فاتح أنيق زهور دعوة', category: 'package', image: '/new cards/بريميوم/وردي وأزرق فاتح أنيق زهور دعوة.png', packageTier: 'premium' },
  { id: "9d9f04e7761f85ca049e9681", name: 'أبيض وأحمر تقليدي زفاف بطاقة', category: 'package', image: '/new cards/بريميوم/أبيض وأحمر تقليدي زفاف بطاقة.png', packageTier: 'premium' },
  { id: "eb85671aa245f33c5c119c25", name: 'Instagram دعوة حفل زفاف خطبة زهور ستوري', category: 'package', image: '/new cards/VIP/Instagram دعوة حفل زفاف خطبة زهور ستوري.png', packageTier: 'vip' },
  { id: "56d7b1793b07c46c9fd6bebb", name: '_دعوة كتب كتاب تصميم دعوة زفاف أزرق فاتح مزخرف', category: 'package', image: '/new cards/VIP/_دعوة كتب كتاب  تصميم دعوة زفاف أزرق فاتح مزخرف .png', packageTier: 'vip' },
  { id: "0d3bc302a0774b874ba78aa5", name: 'أخضر وبيج تقليدي زفاف دعوة', category: 'package', image: '/new cards/VIP/أخضر وبيج تقليدي زفاف دعوة.png', packageTier: 'vip' },
  { id: "491d163ddc38844a6b12dbcb", name: 'أرجواني أبيض زهري رومانسي حفل زواج دعوة (مقاس A6)', category: 'package', image: '/new cards/VIP/أرجواني أبيض زهري رومانسي حفل زواج دعوة (مقاس A6).png', packageTier: 'vip' },
  { id: "01d9138767da5a4fad60651f", name: 'دعوة حفل زفاف 34', category: 'package', image: '/new cards/VIP/دعوة حفل زفاف 34.png', packageTier: 'vip' },
  { id: "9f7795c5c6f7efc778a0277f", name: 'دعوة زواج بنفسجي 3', category: 'package', image: '/new cards/VIP/دعوة زواج بنفسجي 3.png', packageTier: 'vip' },
  { id: "a151bc7b6209e02ecb9d3a02", name: 'دعوة لحفل زفاف باللون الاخضر والزهري مع الزهور', category: 'package', image: '/new cards/VIP/دعوة لحفل زفاف باللون الاخضر والزهري مع الزهور .png', packageTier: 'vip' },
  { id: "d044603bcd3245f8f1513323", name: 'ستوري أعلان حفل زواج أخضر وردي بسيط', category: 'package', image: '/new cards/VIP/ستوري أعلان حفل زواج أخضر وردي بسيط.png', packageTier: 'vip' },
  { id: "406833d71437b0dcee37fbd7", name: 'ستوري أعلان خطوبه بني بسيط', category: 'package', image: '/new cards/VIP/ستوري أعلان خطوبه بني بسيط.png', packageTier: 'vip' },
  { id: "ce778f9242753be7edd00623", name: 'ستوري أعلان قدوم مولود أزرق بسيط', category: 'package', image: '/new cards/VIP/ستوري أعلان قدوم مولود أزرق بسيط.png', packageTier: 'vip' },
  { id: "742f989258c0d9fa33ac0d5c", name: 'ستوري انستجرام دعوة زفاف نمط بسيط لون ابيض و أخضر', category: 'package', image: '/new cards/VIP/ستوري انستجرام دعوة زفاف نمط بسيط لون ابيض و أخضر.png', packageTier: 'vip' },
  { id: "a5179aa2e38319575fa73a42", name: 'ستوري انستجرام لحفل زفاف باللون البني والابيض', category: 'package', image: '/new cards/VIP/ستوري انستجرام لحفل زفاف باللون البني والابيض .png', packageTier: 'vip' },
  { id: "13da8e0a4a2a4cb9bf97665f", name: 'ستوري انستقرام بيج و احمر ورد لدعوة زفاف', category: 'package', image: '/new cards/VIP/ستوري انستقرام بيج و احمر ورد لدعوة زفاف.png', packageTier: 'vip' },
  { id: "4c929f99ac8969543c3e690f", name: 'ستوري دعوة زفاف أخضر و بني بسيط', category: 'package', image: '/new cards/VIP/ستوري دعوة زفاف أخضر و بني بسيط.png', packageTier: 'vip' },
  { id: "536f2cd60812d13d6603a0ee", name: 'ستوري دعوه حفل زواج برتقالي بسيط', category: 'package', image: '/new cards/VIP/ستوري دعوه حفل زواج برتقالي بسيط.png', packageTier: 'vip' },
  { id: "75bdcea4cea12a35d6a920e0", name: 'قصة instagram دعوة لحضور زواج', category: 'package', image: '/new cards/VIP/قصة instagram دعوة لحضور زواج.png', packageTier: 'vip' },
  { id: "b6403191a90c898af28ce4e8", name: 'قصة أرجواني زهري وأبيض أنيق لدعوة زفاف', category: 'package', image: '/new cards/VIP/قصة أرجواني زهري وأبيض أنيق لدعوة زفاف .png', packageTier: 'vip' },
  { id: "b734ca66d70c8d9922e1e03e", name: 'قصة انستجرام باللون الاحمر والبيج لحفل زفاف', category: 'package', image: '/new cards/VIP/قصة انستجرام باللون الاحمر والبيج لحفل زفاف.png', packageTier: 'vip' },
  { id: "316152cdb223aff74c125157", name: 'قصة انستجرام رمادي بتصميم بسيط لاعلان عقد قران', category: 'package', image: '/new cards/VIP/قصة انستجرام رمادي بتصميم بسيط لاعلان عقد قران.png', packageTier: 'vip' },
  { id: "52846cebfd15cb03f45d1985", name: 'قصة انستقرام حفل زواج تصميم لافندر بسيط لون بنفسج', category: 'package', image: '/new cards/VIP/قصة انستقرام حفل زواج تصميم لافندر بسيط لون بنفسج.png', packageTier: 'vip' },
  { id: "f4393c95fae5b8059581806e", name: 'قصة وردي بسيط عن حفلات الزفاف', category: 'package', image: '/new cards/VIP/قصة وردي بسيط عن حفلات الزفاف.png', packageTier: 'vip' },
  { id: "3238efa7c69fc1201d105cf3", name: 'قصتك دعوة زفاف أبيض وأخضر بسيط', category: 'package', image: '/new cards/VIP/قصتك دعوة زفاف أبيض وأخضر بسيط .png', packageTier: 'vip' },
  { id: "b18439b4dd2642f8923de59a", name: 'قصتك دعوة زفاف أبيض وأسود بسيط', category: 'package', image: '/new cards/VIP/قصتك دعوة زفاف أبيض وأسود بسيط .png', packageTier: 'vip' },
  { id: "a309bc32e10628f6b6477cd0", name: 'قصتك دعوة زفاف أحمر وأبيض وزهري بسيط', category: 'package', image: '/new cards/VIP/قصتك دعوة زفاف أحمر وأبيض وزهري بسيط .png', packageTier: 'vip' },
  { id: "ec02fea7de5e8f5177639974", name: 'قصتك دعوة زفاف ذهبي وأبيض بسيط', category: 'package', image: '/new cards/VIP/قصتك دعوة زفاف ذهبي وأبيض بسيط .png', packageTier: 'vip' },
  { id: "e1190c7d3f4003f42de66181", name: 'قصتك دعوة زواج رمادي كلاسيكي بسيط', category: 'package', image: '/new cards/VIP/قصتك دعوة زواج رمادي كلاسيكي بسيط .png', packageTier: 'vip' },
  { id: "8811933652eef8f768bf97d4", name: 'قصتك عن دعوة زواج لون رمادي و أخضر بسيط', category: 'package', image: '/new cards/VIP/قصتك عن دعوة زواج لون رمادي و أخضر بسيط .png', packageTier: 'vip' },
  { id: "aa6c42661d89ffbbc0d322a7", name: 'زهري وأسود بسيط حفل تخرج قصتك', category: 'حفل تخرج', image: '/new cards/تخرج/زهري وأسود بسيط حفل تخرج قصتك.png' },
  { id: "78694e8e9311435de0c37def", name: 'زهري وبني بسيط حفل تخرج قصتك', category: 'حفل تخرج', image: '/new cards/تخرج/زهري وبني بسيط حفل تخرج قصتك.png' },
  { id: "a558b7e87c2e974385214032", name: 'ستوري اعلان حفل تخرج وردي بسيط', category: 'حفل تخرج', image: '/new cards/تخرج/ستوري اعلان حفل تخرج وردي بسيط.png' },
  { id: "ffc2b34397f86b8345581bd2", name: 'ستوري اعلان حفلة تخرج اخضر بسيط', category: 'حفل تخرج', image: '/new cards/تخرج/ستوري اعلان حفلة تخرج اخضر بسيط.png' },
  { id: "6f944c889dae3f4af9b2e083", name: 'قصتك حفل تخرج أبيض وبني بسيط', category: 'حفل تخرج', image: '/new cards/تخرج/قصتك حفل تخرج أبيض وبني بسيط .png' },
  { id: "d5fd793346d35a2995bad539", name: 'قصتك وردي بسيط عن التخرج', category: 'حفل تخرج', image: '/new cards/تخرج/قصتك وردي بسيط عن التخرج.png' },
  { id: "d81831a786392f808de7d182", name: 'أبيض وأخضر بسيط تهنئة مولودة قصتك', category: 'عيد ميلاد', image: '/new cards/مواليد/أبيض وأخضر بسيط تهنئة مولودة قصتك.png' },
  { id: "b3ceb254cbc903dd68b37179", name: 'أخضر فاتح وزهري بسيط تهنئة مولودة قصتك', category: 'عيد ميلاد', image: '/new cards/مواليد/أخضر فاتح وزهري بسيط تهنئة مولودة قصتك.png' },
  { id: "f875362829ea9f395e755da0", name: 'أرجواني وأبيض مرسوم يدوياً حفل ولادة دعوة', category: 'عيد ميلاد', image: '/new cards/مواليد/أرجواني وأبيض مرسوم يدوياً حفل ولادة دعوة.png' },
  { id: "eb10c778fedd5bd90289b153", name: 'أزرق سماوي بسيط عن مولود قصتك', category: 'عيد ميلاد', image: '/new cards/مواليد/أزرق سماوي بسيط عن مولود قصتك.png' },
  { id: "0231ed2e6459e7109cc20081", name: 'أزرق وأسود بسيط عن مولود قصتك', category: 'عيد ميلاد', image: '/new cards/مواليد/أزرق وأسود بسيط عن مولود قصتك.png' },
  { id: "cce9606df712a613a9b4d49d", name: 'بشارة مولود بلون اخضر بنمط منظر طبيعي', category: 'عيد ميلاد', image: '/new cards/مواليد/بشارة مولود بلون اخضر بنمط منظر طبيعي.png' },
  { id: "54f15c4dbf183b01734dd36f", name: 'بشارة مولودة لون الوردي مقاس قصة انستجرام', category: 'عيد ميلاد', image: '/new cards/مواليد/بشارة مولودة لون الوردي  مقاس قصة انستجرام.png' },
  { id: "03a391b385705d35018f6afb", name: 'دعوة أعلان قدوم مولود أزرق بسيط', category: 'عيد ميلاد', image: '/new cards/مواليد/دعوة أعلان قدوم مولود أزرق بسيط.png' },
  { id: "72b20c56da9641446c96250b", name: 'ستوري اعلان قدوم مولود أزرق بسيط', category: 'عيد ميلاد', image: '/new cards/مواليد/ستوري اعلان قدوم مولود أزرق بسيط.png' },
  { id: "12df72c0d072ff39bac9fec2", name: 'ستوري اعلان قدوم مولود اخضر ازرق بسيط مائي', category: 'عيد ميلاد', image: '/new cards/مواليد/ستوري اعلان قدوم مولود اخضر ازرق بسيط مائي.png' },
  { id: "c923385859457be5f5028f99", name: 'ستوري اعلان قدوم مولود بنفسجي بسيط', category: 'عيد ميلاد', image: '/new cards/مواليد/ستوري اعلان قدوم مولود بنفسجي بسيط.png' },
  { id: "b487be77d9f550739b1908cc", name: 'ستوري اعلان قدوم مولود بني بسيط', category: 'عيد ميلاد', image: '/new cards/مواليد/ستوري اعلان قدوم مولود بني بسيط.png' },
  { id: "ca9db1389e644c09c42c1a5e", name: 'ستوري اعلان قدوم مولود رمادي بسيط', category: 'عيد ميلاد', image: '/new cards/مواليد/ستوري اعلان قدوم مولود رمادي بسيط.png' },
  { id: "418a9482445aa25274b6a746", name: 'ستوري انستجرام اللون الروز و ابيض وردي بسيط تهنئة مولود جديد arabic floral story baby born', category: 'عيد ميلاد', image: '/new cards/مواليد/ستوري انستجرام اللون الروز و ابيض وردي بسيط تهنئة مولود جديد arabic floral story baby born .png' },
  { id: "7c513ab0b8d8d022fc13e9dd", name: 'قصة Instagram لمولود جديد بنمط انيق لون وردي', category: 'عيد ميلاد', image: '/new cards/مواليد/قصة Instagram لمولود جديد بنمط انيق لون وردي.png' },
  { id: "452b7e140aeea160cbea577b", name: 'قصة انستقرام اعلان قدوم مولود وردي بسيط', category: 'عيد ميلاد', image: '/new cards/مواليد/قصة انستقرام اعلان قدوم مولود وردي بسيط.png' },
  { id: "81404fdef9a92f649eba24fb", name: 'قصتك أخضر و أبيض بسيط', category: 'عيد ميلاد', image: '/new cards/مواليد/قصتك أخضر و أبيض بسيط .png' },
  { id: "19b12183ce169c997a3b50e7", name: 'قصتك تهنئة مولودة وردي وأبيض بسيط', category: 'عيد ميلاد', image: '/new cards/مواليد/قصتك تهنئة مولودة  وردي وأبيض بسيط .png' },
  { id: "fb811262ef780608b23efa2f", name: 'قصتك تهنئة مولودة زهري وردي بسيط', category: 'عيد ميلاد', image: '/new cards/مواليد/قصتك تهنئة مولودة زهري وردي بسيط .png' },
];
